# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\InvestmentCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 277)
        MainWindow.setMinimumSize(QtCore.QSize(794, 277))
        MainWindow.setMaximumSize(QtCore.QSize(794, 277))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 260, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.calculate_Button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_Button.setGeometry(QtCore.QRect(450, 170, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.calculate_Button.setFont(font)
        self.calculate_Button.setObjectName("calculate_Button")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(440, 20, 213, 120))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.additional_Box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.additional_Box.setGeometry(QtCore.QRect(290, 190, 109, 31))
        self.additional_Box.setObjectName("additional_Box")
        self.rate_Box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.rate_Box.setGeometry(QtCore.QRect(290, 150, 109, 31))
        self.rate_Box.setObjectName("rate_Box")
        self.years_Box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.years_Box.setGeometry(QtCore.QRect(290, 70, 109, 31))
        self.years_Box.setObjectName("years_Box")
        self.initial_Box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.initial_Box.setGeometry(QtCore.QRect(290, 30, 109, 31))
        self.initial_Box.setObjectName("initial_Box")
        self.balance_Label = QtWidgets.QLabel(self.centralwidget)
        self.balance_Label.setGeometry(QtCore.QRect(700, 30, 61, 16))
        self.balance_Label.setObjectName("balance_Label")
        self.start_Amount_Label = QtWidgets.QLabel(self.centralwidget)
        self.start_Amount_Label.setGeometry(QtCore.QRect(700, 60, 47, 13))
        self.start_Amount_Label.setObjectName("start_Amount_Label")
        self.contributions_Label = QtWidgets.QLabel(self.centralwidget)
        self.contributions_Label.setGeometry(QtCore.QRect(700, 90, 47, 13))
        self.contributions_Label.setObjectName("contributions_Label")
        self.Interest_Label = QtWidgets.QLabel(self.centralwidget)
        self.Interest_Label.setGeometry(QtCore.QRect(700, 120, 47, 13))
        self.Interest_Label.setObjectName("Interest_Label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(290, 110, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Investment Calculator"))
        self.label.setText(_translate("MainWindow", "Starting Amount ($)"))
        self.label_2.setText(_translate("MainWindow", "Number of Years"))
        self.label_4.setText(_translate("MainWindow", "Compound"))
        self.label_3.setText(_translate("MainWindow", "Return Rate (%)"))
        self.label_5.setText(_translate("MainWindow", "Additional Contributions ($)"))
        self.calculate_Button.setText(_translate("MainWindow", "Calculate"))
        self.label_10.setText(_translate("MainWindow", "Balance ($)"))
        self.label_6.setText(_translate("MainWindow", "Starting Amount ($)"))
        self.label_7.setText(_translate("MainWindow", "Total Contributions ($)"))
        self.label_8.setText(_translate("MainWindow", "Total from Interest ($)"))
        self.rate_Box.setPlainText(_translate("MainWindow", "6"))
        self.years_Box.setPlainText(_translate("MainWindow", "10"))
        self.initial_Box.setPlainText(_translate("MainWindow", "20000"))
        self.balance_Label.setText(_translate("MainWindow", "0.00"))
        self.start_Amount_Label.setText(_translate("MainWindow", "0.00"))
        self.contributions_Label.setText(_translate("MainWindow", "0.00"))
        self.Interest_Label.setText(_translate("MainWindow", "0.00"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Annually"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Semi-Annually"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Quarterly"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Monthly"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Semi-Monthly"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Biweekly"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Weekly"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Daily"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Continuously "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

